# Window Setting Values
TITLE = 'BMONG US'
DISPLAY_WIDTH = 960
DISPLAY_HEIGHT = 720
FPS = 30

LIMIT_LEFT = 10
LIMIT_RIGHT = DISPLAY_WIDTH - 10
LIMIT_TOP = 10
LIMIT_BOTTOM = DISPLAY_HEIGHT - 10

# Color Values
WHITE = (255,255,255)
BLACK = (0,0,0)

# Action Values
IDLE = 5
WALK_LEFT = 4 
WALK_RIGHT = 6
WALK_UP = 8
WALK_DOWN = 2
WALK = 11
SABOTAGE = 12
KILL = 13
DEAD = 14
REVIVE = 15

# Animation Values
MOVE_SPEED = 7
WALK_ANIMATION_FRAME = 12
DEAD_ANIMATION_FRAME = 40
SPAWN_ANIMATION_FRAME = 49

# Background Values
BG_IDLE = 5
BG_MOVE_LEFT = 4
BG_MOVE_RIGHT = 6
BG_MOVE_UP = 8
BG_MOVE_DOWN = 2
BG_MOVE_SPEED = 5

TABLE_POS_X = 485
TABLE_POS_Y = 370

# Button Values
KILL_BUTTON_X = 780
KILL_BUTTON_Y = DISPLAY_HEIGHT - 15
SABOTAGE_BUTTON_X = 880
SABOTAGE_BUTTON_Y = DISPLAY_HEIGHT - 15
REVIVE_BUTTON_X = DISPLAY_WIDTH - 15
REVIVE_BUTTON_Y = 15

MOUSE_LEFT = 0
MOUSE_RIGHT = 2

# Face Side Value
FACE_LEFT = 4
FACE_RIGHT = 6